USE [master]
GO
/****** Object:  Database [EcommerceAppDB]    Script Date: 2023/11/19 10:47:49 ******/
CREATE DATABASE [EcommerceAppDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EcommerceAppDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EcommerceAppDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EcommerceAppDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EcommerceAppDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [EcommerceAppDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EcommerceAppDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EcommerceAppDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EcommerceAppDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EcommerceAppDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [EcommerceAppDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EcommerceAppDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET RECOVERY FULL 
GO
ALTER DATABASE [EcommerceAppDB] SET  MULTI_USER 
GO
ALTER DATABASE [EcommerceAppDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EcommerceAppDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EcommerceAppDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EcommerceAppDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EcommerceAppDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EcommerceAppDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EcommerceAppDB', N'ON'
GO
ALTER DATABASE [EcommerceAppDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [EcommerceAppDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [EcommerceAppDB]
GO
/****** Object:  Table [dbo].[CUSTOMERS]    Script Date: 2023/11/19 10:47:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMERS](
	[CUSTOMERID] [int] IDENTITY(1,1) NOT NULL,
	[FIRSTNAME] [nvarchar](50) NULL,
	[LASTNAME] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[HOUSENO] [nvarchar](50) NULL,
	[STREET] [nvarchar](50) NULL,
	[TOWN] [nvarchar](50) NULL,
	[POSTCODE] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDERITEMS]    Script Date: 2023/11/19 10:47:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERITEMS](
	[ORDERITEMID] [int] IDENTITY(1,1) NOT NULL,
	[ORDERID] [int] NULL,
	[PRODUCTID] [int] NULL,
	[QUANTITY] [int] NULL,
	[PRICE] [decimal](9, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ORDERITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDERS]    Script Date: 2023/11/19 10:47:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[ORDERID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMERID] [nvarchar](10) NULL,
	[ORDERDATE] [date] NULL,
	[DELIVERYEXPECTED] [date] NULL,
	[CONTAINSGIFT] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ORDERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTS]    Script Date: 2023/11/19 10:47:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTS](
	[PRODUCTID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTNAME] [nvarchar](50) NULL,
	[COLOUR] [nvarchar](20) NULL,
	[SIZE] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRODUCTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERITEMS]  WITH CHECK ADD FOREIGN KEY([ORDERID])
REFERENCES [dbo].[ORDERS] ([ORDERID])
GO
ALTER TABLE [dbo].[ORDERITEMS]  WITH CHECK ADD FOREIGN KEY([PRODUCTID])
REFERENCES [dbo].[PRODUCTS] ([PRODUCTID])
GO
/****** Object:  StoredProcedure [dbo].[_checkCustomerByEmail]    Script Date: 2023/11/19 10:47:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[_checkCustomerByEmail] @userEmail nvarchar(50)
AS
BEGIN

SELECT COUNT(CUSTOMERID) FROM CUSTOMERS where EMAIL = @userEmail

END
GO
/****** Object:  StoredProcedure [dbo].[_getCustomerByEmail]    Script Date: 2023/11/19 10:47:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[_getCustomerByEmail] @userEmail nvarchar(50)
AS
BEGIN

SELECT FirstName, LastName FROM CUSTOMERS where EMAIL = @userEmail

END
GO
/****** Object:  StoredProcedure [dbo].[_getMostRecentOrdeForUser]    Script Date: 2023/11/19 10:47:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[_getMostRecentOrdeForUser] @userEmail nvarchar(50)
AS
BEGIN

SELECT TOP 1 O.ORDERID as orderNumber, O.orderDate as orderDate, C.FIRSTNAME+' '+C.LASTNAME+', '+C.TOWN+', '+C.STREET+', '+C.POSTCODE+', '+C.HOUSENO as deliveryAddress, 
O.DELIVERYEXPECTED as deliveryExpected from CUSTOMERS C
inner join ORDERS O on C.CUSTOMERID = O.CUSTOMERID where C.EMAIL = @userEmail order by O.ORDERID desc

END
GO
/****** Object:  StoredProcedure [dbo].[_getOrderItems]    Script Date: 2023/11/19 10:47:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[_getOrderItems] @userEmail nvarchar(50)
AS
BEGIN

SELECT case when(O.CONTAINSGIFT = 0) then 'Gift' else  P.PRODUCTNAME end as product, OT.QUANTITY as quantity, OT.PRICE as priceEach from CUSTOMERS C
inner join ORDERS O on C.CUSTOMERID = O.CUSTOMERID inner join ORDERITEMS OT on O.ORDERID = OT.ORDERID 
inner join PRODUCTS P on P.PRODUCTID = OT.PRODUCTID where C.EMAIL = @userEmail

END
GO
USE [master]
GO
ALTER DATABASE [EcommerceAppDB] SET  READ_WRITE 
GO
